### ISSUE TITLE
Pull dependencies from support repository instead of jar file

### ISSUE THREAD

**Issue by ghost** [varlesh/elementary-style#14]
Using `compile 'com.android.support:support-v4:21.0.0'` (replace 21.0.0 with whatever version is used) instead of `compile files('libs/android-support-v4.jar')` in build.gradle would make the jar unnecessary.

**Comment by varlesh** [comment]
https://github.com/varlesh/theia-icon-theme/commit/86f062a5d466006e3a287ae91056f8fc94e26958
