### ISSUE TITLE
Bump minSdkVersion

### ISSUE THREAD

**Issue by ghost** [varlesh/elementary-style#15]
Remove minSdk from the AndroidManifest.xml or bump it at least to 4 to avoid conflicts with support-v4. In gradle you can set it via  `minSdkVersion 4`.

For reference: In fdroid I currently apply the following modifications: `sed -i -e 's/v4:22.0.1/v4:22.0.0/g' -e '/target/aminSdkVersion 4'  build.gradle`

**Comment by png2378** [comment]
e773f3abed849cf4f6bbdb1cd6ed267212836972
