### ISSUE TITLE
Djaler request

### ISSUE THREAD

**Issue by h1royuki** [varlesh/elementary-style#16]
- [x] [Переводчик Google](https://play.google.com/store/apps/details?id=com.google.android.apps.translate)
- [x] [AdAway](https://f-droid.org/repository/browse/?fdid=org.adaway)
- [x] [Cabinet BETA](https://play.google.com/store/apps/details?id=com.afollestad.cabinet)
- [x] [DriveDroid](https://play.google.com/store/apps/details?id=com.softwarebakery.drivedroid)
- [x] [Dropsync](https://play.google.com/store/apps/details?id=com.ttxapps.dropsync)
- [x] [Endomondo](https://play.google.com/store/apps/details?id=com.endomondo.android)
- [x] [Fleksy](https://play.google.com/store/apps/details?id=com.syntellia.fleksy.keyboard)
- [x] [Greenify](https://play.google.com/store/apps/details?id=com.oasisfeng.greenify)
- [x] [OLX.ua](https://play.google.com/store/apps/details?id=ua.slando)
- [x] [Приват24](https://play.google.com/store/apps/details?id=ua.privatbank.ap24)
- [x] [Smiler Reborn](https://play.google.com/store/apps/details?id=ru.droidlab.smiler)
- [x] [Talon for Twitter](https://play.google.com/store/apps/details?id=com.klinker.android.twitter_l&hl=ru)
- [x] [Titanium Backup](https://play.google.com/store/apps/details?id=com.keramidas.TitaniumBackup)
- [x] [Wakelock Detector](https://play.google.com/store/apps/details?id=com.uzumapps.wakelockdetector)

**Comment by h1royuki** [comment]
Google Translate c402817c4bea94417746580f239ba6a50136b4df

**Comment by h1royuki** [comment]
Talon, Kate Mobile, Калькулятор++ fd30c5125d5ec068c6d1b7fc2ff6631ed003cc08

**Comment by h1royuki** [comment]
Cabinet BETA, AdAway 5591fdd851385b9e4c224e52368e1c1024ee4df7
AdAway - need icon.

**Comment by h1royuki** [comment]
f6489f4356137fdd89bc636274a0ba1215418fa0
Dropsync, Drive Droid - need icons.

**Comment by varlesh** [comment]
ba33ece0c10a9c385404c1e458dbfdddd706117c

**Comment by varlesh** [comment]
0042e0205b1ebd2bc80daa15b1754a2d0cf5862c

**Comment by h1royuki** [comment]
Fleksy, Greenify a3739f826d8b8332775e6f4e4c7fa26ddca77bb7

**Comment by h1royuki** [comment]
Приват 24 46e0e941bc748dcd39d8ff96093e1f8e35c10d35

**Comment by varlesh** [comment]
All Added!
7ae9d855a694f5eb845d83b46dd2ac6402cfe875
f06a8f320fd2bcf87ba21e53c718f6ac22bdb70e
b6d6177c2c76d6bfd72fa487eca19607660c6557
