### ISSUE TITLE
My Icon Request.

### ISSUE THREAD

**Issue by ghost** [varlesh/elementary-style#25]
- [x] [2048++](https://play.google.com/store/apps/details?id=com.alexjlockwood.twentyfortyeight)
- [x] [Advanced Download Manager](https://play.google.com/store/apps/details?id=com.dv.adm)
- [x] [Motorola Alert](https://play.google.com/store/apps/details?id=com.motorola.bodyguard)
- [x] [Motorola Assist](https://play.google.com/store/apps/details?id=com.motorola.contextual.smartrules2)
- [x] [Audio Recorder](https://play.google.com/store/apps/details?id=com.sonymobile.androidapp.audiorecorder)
- [x] [Duolingo](https://play.google.com/store/apps/details?id=com.duolingo)
- [x] [FM Radio](https://play.google.com/store/apps/details?id=com.motorola.fmplayer)
- [x] [Motorola Galery](https://play.google.com/store/apps/details?id=com.motorola.MotGallery2)
- [x] [Hangouts](https://play.google.com/store/apps/details?id=com.google.android.talk)
- [x] [Motorola Help](https://play.google.com/store/apps/details?id=com.motorola.genie)
- [x] [Motorola Migrate](https://play.google.com/store/apps/details?id=com.motorola.migrate)
- [x] [Google News and Weather](https://play.google.com/store/apps/details?id=com.google.android.apps.genie.geniewidget)
- [x] [Opera Max](https://play.google.com/store/apps/details?id=com.opera.max.global)
- [x] [Google Play NewsStand](https://play.google.com/store/apps/details?id=com.google.android.apps.magazines)
- [x] [PocketBook Reader](https://play.google.com/store/apps/details?id=com.obreey.reader)
- [x] [ShareIt](https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps)
- [x] [Google Slides](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.slides)
- [x] [Wikipedia](https://play.google.com/store/apps/details?id=org.wikipedia)

**Comment by varlesh** [comment]
Audio Recorder, Opera Max, Google Play  прописать в appfilter.xml класс приложения.

**Comment by png2378** [comment]
И FM Radio. А вот Opera Max не нашел в icon-source.

**Comment by varlesh** [comment]
Все необходимые значки добавлены в svg и png, обновлен drawable.xml и iconpack.xml 05cc0510c7fd9e66aa08fba38e86958d6ec0b7f2
Необходимо указать класс приложения для новых значков в appfilter.xml.

Имеются иконки для:
Audio Recorder (com_android_soundrecorder)
FM Radio (com_android_radio)
PocketBook Reader (org_geometerplus_zlibrary_ui_android)
Для них тоже нужно указать класс приложения в appfilter.xml.

**Comment by varlesh** [comment]
Добавлены классы для некоторых приложений найденыx в базе 440a085f61b7b1a71a896d5260587b1f584ededa

**Comment by varlesh** [comment]
b5da2c564918a4fdcfedf17bf8681aad7e75044d
